### ISSUE TITLE
Examples / Примеры подключения

### ISSUE THREAD

**Issue by getfm** [salterok/VK-2-years-old-#1]
Приведите пожалуйста здесь пример авторизации с последующим выполнение любого метода.

**Comment by salterok** [comment]
к сожелению библиотека на данный момент не предназначена для использования
и реализованы только API из групп: Audio, Friends, Messages, Groups, Notification, Newsfeeds

добавлено небольшое описание и там же простейший пример
https://github.com/SalterOk/VK/wiki
